
export const ACTION_AUTHORIZE = {
    checkAuthUser: 'ACTION_AUTHORIZE_CHECK_AUTH_USER',
    setLoading: 'ACTION_AUTHORIZE_SET_LOADING',
    setError: 'ACTION_AUTHORIZE_SET_ERROR',
    setAccessToken: 'ACTION_AUTHORIZE_SET_ACCESS_TOKEN'
};
